### ISSUE TITLE
React 16 compatibility?

### ISSUE THREAD

**Issue by schwers-zz** [dazld/react-on-visible#16]
apologies if this is a duplicate, but is this library compatible with react 16? When I tried upgrading I'm getting the following error in `React`

![image](https://user-images.githubusercontent.com/307983/31966370-58cf9572-b8bf-11e7-82cc-8427fed69dab.png)

I believe this is due to lines:

https://github.com/dazld/react-on-visible/blob/master/src/index.js#L39

and

https://github.com/dazld/react-on-visible/blob/master/src/index.js#L47

The react docs specify that the first argument should be a function that returns `state` when the second callback param is used https://reactjs.org/docs/react-component.html#setstate

**Comment by dazld** [comment]
fixed in #17
