### ISSUE TITLE
Class is not being added when div comes into view.

### ISSUE THREAD

**Issue by Richard-Thompson** [dazld/react-on-visible#22]
I am trying to get this package to work but it wont add the appear class to the container div no matter what i try and do. Think its a bug. Im using React v16.2.0. This is my code below:
```javascript
import React from 'react';
import OnVisible, { setDefaultProps } from 'react-on-visible';

setDefaultProps({
    bounce: true,
    visibleClassName: 'appear',
    percent: 100
});

export default function Card (props) {
    return (
      <div>
        <OnVisible className="my-container">
         <div id='article'></div>
         </OnVisible>
      </div>
       );
     
   }
```

**Comment by Richard-Thompson** [comment]
ok this can be closed, the root div had a height in vh and this was messing with adding the class onto the container div.

**Comment by dazld** [comment]
glad you figured it out! feel free to reopen if it was something else.
