### ISSUE TITLE
onChange doesn't behave as described in docs

### ISSUE THREAD

**Issue by 0xsven** [dazld/react-on-visible#27]
Expected:
"Callback when visibility changes. Argument is a boolean, true for visible, false for not."

Actual:
Callback when scrolling and element in viewport. Argument is always true. Maybe rename it to `onVisible` or `onScrollAndVisible` (when bounce true). 

Correction: It actually works when scrolling back up. So it checks if the viewport is below or above the element. But not if the element is in the viewport.

**Comment by dazld** [comment]
that sounds like a bug - it should call with false when the element exits the viewport.

**Comment by animify** [comment]
Any update on this? Coming across the same issue

**Comment by dazld** [comment]
sorry for delay @animify  and @0xsven - this is fixed in `1.5.1` and should be available now :)
